### ISSUE TITLE
Executable "hangs" when first argument left out

### ISSUE THREAD

**Issue by amar47shah** [amar47shah/record-parser#10]
Strange behavior when running:
bin/record-parser data/commas.txt

Expected:
some kind of error message because instruction not given.

Instead:
appears to hang, after interrupt, get:
.../record-parser/lib/record_parser/command_line_interface.rb:31:in `read': Interrupt
	from .../record-parser/lib/record_parser/command_line_interface.rb:31:in `unsorted_records'
	from .../record-parser/lib/record_parser/command_line_interface.rb:10:in `run'
	from bin/record-parser:5:in `<main>'

Is it trying to read from $stdin?

**Comment by amar47shah** [comment]
"If ARGV is empty, then ARGF operates on STDIN instead."
http://heyrod.com/snippet/s/ruby-argf-basics.html

**Comment by amar47shah** [comment]
Fixed in bdd796c.
